<?php

// autoload.php generated by Composer

require_once t3lib_extMgm::extPath('geckoboard') . 'Resources/Private/PHP/composer/autoload_real.php';

return ComposerAutoloaderInit9fed199b2dbe428b427421150ce2ecb5::getLoader();
